<?php $subs = $this->getCategoryCollection($this->getCategoryId()) ?>
<?php if ($subs->count() > 0): ?>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" aria-hidden="true">
        <?php foreach ($subs as $_subcat): ?>
            <li class="level<?php echo $block->getLevel($_subcat) ?> first parent ui-menu-item<?php if ($block->isActive($_subcat)): ?> active<?php endif; ?>" role="presentation">
                <a href="<?php echo $_subcat->getUrl() ?>" aria-haspopup="true" class="ui-corner-all" tabindex="-1" role="menuitem">
                    <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span>
                    <span><?php echo $_subcat->getName() ?></span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>